fxaide:
  service:
    port: 10240

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:9092/~/db-fxaide
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

logging:
  level:
    org.springframework: INFO
    org.hibernated: INFO
    root: ERROR
    net.fixfixt: DEBUG